# This file was generated by GoReleaser. DO NOT EDIT.
cask "sprout" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a165fe8c2753174821c605c15c90039f9256620e03e6646a4e577f39f5f10e18"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "66a11656127a4afac04b7fb893281001762f8f422a5672ea6df89c8ba5c92aa6"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "816d06a660c58543db312a9232d107047f21c9b55cc7b4a873a1cacd8070bf45"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e955425cdcc94772975eeb4b53623b4eb5e6da2d8cda7f9b20f04f8850df7873"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sprout"
  desc "Map your codebase for you and your AI agent"
  homepage "https://sprout-devlabs.github.io/sprout-web/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sprout"
  manpage "manpages/sprout.1"
  bash_completion "completions/sprout.bash"
  fish_completion "completions/sprout.fish"
  zsh_completion "completions/_sprout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sprout"]
    end
  end

  # No zap stanza required
end
