# This file was generated by GoReleaser. DO NOT EDIT.
cask "sprout" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "39efe95755f13df7096581535aeda4be96bf03d5d9f498b8428e3019a6b9e6c7"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b7fa99298c719cedc393ca16d0118ac281f09772a6cdb064a720fe99dbabe9a"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b3511c690de0eb5cb12870e23e071df0c38f23e1b88e391c8f8db27fd99c9d6"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "449fff0102f7b4f13e1bdbe44dc0fea3d1bb17a30d18270d1e69686a496e072c"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sprout"
  desc "Map your codebase for you and your AI agent"
  homepage "https://sprout-devlabs.github.io/sprout-web/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sprout"
  manpage "manpages/sprout.1"
  bash_completion "completions/sprout.bash"
  fish_completion "completions/sprout.fish"
  zsh_completion "completions/_sprout"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/sprout"],
          writable_paths: ["sprout"],
          writable_base:  :staged_path
    end
  end

  # No zap stanza required
end
