# This file was generated by GoReleaser. DO NOT EDIT.
cask "sprout" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "7803cb316dd577e9c6bb71a60f66eda32ab4b73cfd351814570317b4d1da7c3a"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e019f2af96683f1e5ac710aaf2ab6ea5ff686533bdb7e7f68a4e4f1811ee378f"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e81509c1cc1dbff4dabc3521738b8602e437da5678ab911d9ac3947fd1b9cbb8"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "23ad356bf155f0f1b1920a5ef37096d1a3a881715e0326b655e2b2a037ffcef9"
      url "https://github.com/Sprout-DevLabs/sprout/releases/download/v#{version}/sprout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sprout"
  desc "Map your codebase for you and your AI agent"
  homepage "https://sprout-devlabs.github.io/sprout-web/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sprout"
  manpage "manpages/sprout.1"
  bash_completion "completions/sprout.bash"
  fish_completion "completions/sprout.fish"
  zsh_completion "completions/_sprout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sprout"]
    end
  end

  # No zap stanza required
end
